---
- name: Download Rust installer
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'

- name: Install Rust
    shell: |
      /tmp/sh.rustup.rs -y
      [ -f ~/.cargo/env ] && source $HOME/.cargo/env
